sonar.projectKey=luigigigabyte
sonar.organization=LuigiGigabyte

# This is the relative path to the source code
sonar.sources=.
sonar.exclusions=static/**, **/test_*.py

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Python specific settings
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
